services:
  web:
    build: .
    network_mode: "host"  # Use host network mode to allow WoL packets to reach physical network
    cap_add:
      - NET_RAW
    volumes:
      - db_data:/app/instance
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_CONFIG=production
      - FLASK_DEBUG=0
      - SECRET_KEY=dev-key-change-in-production
      - WTF_CSRF_SECRET_KEY=csrf-secret-key-change-in-production
      - REDIS_URL=redis://localhost:6379/0  # Updated to use localhost since we're in host network mode
      - SESSION_COOKIE_DOMAIN=
      - SESSION_COOKIE_SECURE=False
    entrypoint: ["/app/entrypoint.sh"]
    restart: unless-stopped

volumes:
  db_data:

