services:
  web:
    build: .
    ports:
      - "8008:8080"
    volumes:
      - db_data:/app/instance
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_CONFIG=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-key-change-in-production
    restart: unless-stopped

volumes:
  db_data:

